// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Veltris.Api.Infrastructure.Data;

#nullable disable

namespace Veltris.Api.Migrations
{
    [DbContext(typeof(VeltrisDbContext))]
    [Migration("20260821222514_DomainModeli")]
    partial class DomainModeli
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("KurumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihiUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SifreOzeti")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("SonGirisTarihiUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("KurumId", "Eposta")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.KullaniciRol", b =>
                {
                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.HasKey("KullaniciId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("KullaniciRolleri", (string)null);
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Kurum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturulmaTarihiUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("Kurumlar", (string)null);
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KurumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihiUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SistemRolu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KurumId", "Ad")
                        .IsUnique();

                    b.ToTable("Roller", (string)null);
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.RolYetki", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("YetkiId")
                        .HasColumnType("uuid");

                    b.HasKey("RolId", "YetkiId");

                    b.HasIndex("YetkiId");

                    b.ToTable("RolYetkileri", (string)null);
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Yetki", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Yetkiler", (string)null);
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("Veltris.Api.Domain.Entities.Kurum", "Kurum")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.KullaniciRol", b =>
                {
                    b.HasOne("Veltris.Api.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veltris.Api.Domain.Entities.Rol", "Rol")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Rol", b =>
                {
                    b.HasOne("Veltris.Api.Domain.Entities.Kurum", "Kurum")
                        .WithMany()
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.RolYetki", b =>
                {
                    b.HasOne("Veltris.Api.Domain.Entities.Rol", "Rol")
                        .WithMany("RolYetkileri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veltris.Api.Domain.Entities.Yetki", "Yetki")
                        .WithMany("RolYetkileri")
                        .HasForeignKey("YetkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciRolleri");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Kurum", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Rol", b =>
                {
                    b.Navigation("KullaniciRolleri");

                    b.Navigation("RolYetkileri");
                });

            modelBuilder.Entity("Veltris.Api.Domain.Entities.Yetki", b =>
                {
                    b.Navigation("RolYetkileri");
                });
#pragma warning restore 612, 618
        }
    }
}
